version: '3.1'

services:
    mysqldb:
        container_name: mysqldb
        image: mysql
        command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        ports:
            - "127.0.0.1:13306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: 123456

    redisdb:
        container_name: redisdb
        image: redis
        restart: always
        ports:
            - "127.0.0.1:16379:6379"

    postgresql-master:
        container_name: postgresdb
        image: docker.io/bitnami/postgresql:12
        ports:
            - '127.0.0.1:15432:5432'
        environment:
            - POSTGRESQL_REPLICATION_MODE=master
            - POSTGRESQL_REPLICATION_USER=postgres
            - POSTGRESQL_REPLICATION_PASSWORD=123456
            - POSTGRESQL_USERNAME=postgres
            - POSTGRESQL_PASSWORD=123456
            - POSTGRESQL_DATABASE=testing
            - ALLOW_EMPTY_PASSWORD=yes

    mongo:
        container_name: mongo
        image: mongo
        restart: always
        ports:
            - '127.0.0.1:27017:27017'
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=example

