version: '3.1'

services:
    mysqldb:
        container_name: mysqldb
        image: mysql
        command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        ports:
            - "127.0.0.1:13306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=123456

    redisdb:
        container_name: redisdb
        image: redis
        ports:
            - "127.0.0.1:16379:6379"

    postgresql:
        container_name: postgresdb
        image: postgres
        ports:
            - "127.0.0.1:15432:5432"
        environment:
            - POSTGRESQL_PASSWORD=123456

    mongo:
        container_name: mongo
        image: mongo
        ports:
            - "127.0.0.1:27017:27017"
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=123456

